name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "./"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "./"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      LIBRARIES: |
        # Install the Arduino_ConnectionHandler library from the repository
        - source-path: ./
        - name: ESP8266WiFi
        - name: WiFiClient
        - name: ESP8266WebServer
        - name: ESP8266mDNS
        - name: FS
        - name: WiFiManager
        - name: SPIFFS
        - name: ArduinoJson
      ARDUINOCORE_MBED_STAGING_PATH: extras/ArduinoCore-mbed
      ARDUINOCORE_API_STAGING_PATH: extras/ArduinoCore-API
      SKETCHES_REPORTS_PATH: sketches-reports
    strategy:
      matrix:
        board:
          - fqbn: "esp8266:esp8266:LOLIN(WEMOS) D1 R2 & mini"
            platform-name: esp8266:esp8266
          - fqbn: "esp32:esp32:esp32"
            platform-name: esp32:esp32

        # Make board type-specific customizations to the matrix jobs
        include:
         
          - board:
              platform-name: esp8266:esp8266
            platforms: |
              # Install ESP8266 platform via Boards Manager
              - name: esp8266:esp8266
                source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
                version: 2.5.0

    steps:
      - uses: actions/checkout@v3

      # It's necessary to checkout the platform before installing it so that the ArduinoCore-API dependency can be added
      - name: Checkout ArduinoCore-mbed
        # this step only needed when the Arduino mbed-Enabled Boards platform sourced from the repository is being used
        if: matrix.board.platform-name == 'arduino:mbed'
        uses: actions/checkout@v3
        with:
          repository: arduino/ArduinoCore-mbed
          # The arduino/actions/libraries/compile-examples action will install the platform from this path
          path: ${{ env.ARDUINOCORE_MBED_STAGING_PATH }}

      - name: Checkout ArduinoCore-API
        # This step only needed when the Arduino mbed-Enabled Boards platform sourced from the repository is being used
        if: matrix.board.platform-name == 'arduino:mbed'
        uses: actions/checkout@v3
        with:
          repository: arduino/ArduinoCore-API
          path: ${{ env.ARDUINOCORE_API_STAGING_PATH }}

      - name: Install ArduinoCore-API
        # This step only needed when the Arduino mbed-Enabled Boards platform sourced from the repository is being used
        if: matrix.board.platform-name == 'arduino:mbed'
        run: |
          mv "${{ env.ARDUINOCORE_API_STAGING_PATH }}/api" "${{ env.ARDUINOCORE_MBED_STAGING_PATH }}/cores/arduino"

      - name: Install ESP32 platform dependencies
        if: matrix.board.platform-name == 'esp32:esp32'
        run: pip3 install pyserial

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: ${{ env.LIBRARIES }}
          enable-deltas-report: 'true'
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
